<?php
require_once __DIR__ . '/../config/koneksi.php';
require_login();
if(!$conn)die('Data tidak dapat ditampilkan.');
$id=(int)($_GET['id']??0);
$result=mysqli_query($conn,"SELECT p.*,k.nip,k.nama_karyawan,j.nama_jabatan FROM payroll p JOIN karyawan k ON k.id_karyawan=p.id_karyawan JOIN jabatan j ON j.id_jabatan=k.id_jabatan WHERE p.id_payroll=$id LIMIT 1");
$row=$result?mysqli_fetch_assoc($result):null;
if(!$row){set_flash('warning','Rincian gaji tidak ditemukan.');redirect('transaksi/payroll.php');}
?>
<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rincian Gaji</title><link rel="icon" type="image/png" href="<?= asset('img/favicon.png') ?>"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="<?= asset('css/style.css') ?>" rel="stylesheet"></head><body><div class="container py-4"><div class="text-end mb-3 no-print"><button onclick="window.print()" class="btn btn-dark">Cetak</button> <a href="<?= url('transaksi/payroll.php') ?>" class="btn btn-secondary">Kembali</a></div><div class="card print-card shadow-sm p-4"><div class="text-center mb-4"><img src="<?= asset('img/logo.png') ?>" style="height:80px" alt="Logo"><h1 class="h3 mt-3">SLIP GAJI</h1><div>PT Star Samudera Logistik</div><div class="text-muted">Periode <?= e($row['bulan'].' '.$row['tahun']) ?></div></div>
<div class="row mb-4"><div class="col-6"><strong>NIP</strong>: <?= e($row['nip']) ?><br><strong>Nama</strong>: <?= e($row['nama_karyawan']) ?><br><strong>Jabatan</strong>: <?= e($row['nama_jabatan']) ?></div><div class="col-6 text-end"><strong>Status</strong>: <?= e($row['status_pembayaran']) ?><br><strong>Tanggal Bayar</strong>: <?= e($row['tanggal_pembayaran']??'-') ?></div></div>
<table class="table table-bordered"><tr><th>Komponen</th><th>Perhitungan</th><th>Jumlah</th></tr><tr><td>Gaji Pokok</td><td>-</td><td><?= rupiah($row['gaji_pokok']) ?></td></tr><tr><td>Lembur</td><td><?= $row['jam_lembur'] ?> jam × <?= rupiah($row['tarif_lembur']) ?></td><td><?= rupiah($row['total_lembur']) ?></td></tr><tr><td>Tunjangan</td><td>-</td><td><?= rupiah($row['total_tunjangan'] ?? 0) ?></td></tr><tr><td>Potongan Alpha</td><td><?= $row['jumlah_alpha'] ?> hari × <?= rupiah($row['tarif_alpha']) ?></td><td>− <?= rupiah($row['total_potongan_alpha']) ?></td></tr><tr class="table-primary"><th colspan="2">Total Gaji Bersih</th><th><?= rupiah($row['total_gaji_bersih']) ?></th></tr></table>
<div class="row text-center mt-5"><div class="col-6"><p>Mengetahui,</p><div style="height:70px"></div><strong>Pimpinan</strong></div><div class="col-6"><p>Admin Payroll,</p><div style="height:70px"></div><strong>Administrator</strong></div></div></div></div></body></html>
